name: 'CI: Unit'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build TypeScript
        run: yarn run build

      - name: Run tests
        run: yarn run test

      - name: Codecov
        uses: codecov/codecov-action@v1.0.15
        with:
          flags: unit
          token: ${{ secrets.CODECOV_TOKEN }}
