name: Publish

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  test-unit:
    uses: ./.github/workflows/ci-unit.yml
    secrets: inherit

  test-e2e:
    uses: ./.github/workflows/ci-e2e.yml
    secrets: inherit

  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      NPM_TOKEN: ${{secrets.NPM_TOKEN}}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: yarn

      - run: yarn install --frozen-lockfiles
      - run: yarn run semantic-release
